### ISSUE TITLE
[BE] ERD 작성

### ISSUE THREAD

**Issue by 23Yong** [codesquad-2023-kiosk-team01/kiosk-max#1]
## AS-IS
카페 키오스크 프로젝트의 ERD가 작성되지 않은 상태이다.

## TO-BE
카페 키오스크 프로젝트의 ERD를 작성한다.

**Comment by 23Yong** [comment]
![image](https://github.com/codesquad-2023-kiosk-team01/kiosk-max/assets/66981851/1362abd0-e4e5-4aff-9ed8-feed20c276eb)

**Comment by crtEvent** [comment]
![K-20230620-044625](https://github.com/codesquad-2023-kiosk-team01/kiosk-max/assets/86359180/7174b45a-fbc1-420d-afa9-543f26f109bd)

**Comment by takealook97** [comment]
![image](https://github.com/codesquad-2023-kiosk-team01/kiosk-max/assets/118447769/e8a8187e-46e4-44ea-83c1-4502e7e906df)
ERD나 워크벤치를 처음써봐서 아직 많이 서툰것같습니다.. 좀더 공부해보겠습니다

**Comment by Ojeegu** [comment]
![kiosk_ERD](https://github.com/codesquad-2023-kiosk-team01/kiosk-max/assets/107015624/eb9f658e-bd0e-44c7-8b20-e33410b3361b)
